name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest from Hugging Face remote (favor local README.md)
        run: |
          git fetch https://huggingface.co/spaces/PeterPumpkin/Search_Engine_llm main
          git checkout FETCH_HEAD -- README.md || true
          git add README.md
          git commit -m "Keep local README.md" || true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://PeterPumpkin:$HF_TOKEN@huggingface.co/spaces/PeterPumpkin/Search_Engine_llm main
